#!/bin/sh

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy

echo "SSH Key copied to clipboard! Open https://github.com/account/ssh to add your key"

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update
  
echo "Installing Git Version Control..."
  brew install git

echo "Installing Phantom JS for Javascript testing..."
  brew install phantomjs
  
echo "Installing Node..."
  brew install node

echo "Install NPM (Node Package Manager)..."
  curl http://npmjs.org/install.sh | sh

echo "Installing RVM (Ruby Version Manager)..."
  curl -L https://get.rvm.io | bash -s stable --ruby

echo "Updating Rubygems..."
  gem update --system

echo "Installing PHP..."
  brew tap josegonzalez/homebrew-php
  brew install php53 --with-mysql --with-intl

curl -s https://raw.github.com/anthonyshort/laptop/master/ruby | sh
curl -s https://raw.github.com/anthonyshort/laptop/master/node | sh
curl -s https://raw.github.com/anthonyshort/laptop/master/php | sh
