#!/bin/sh
  
echo "Installing Coffeescript..."
  npm install -g coffee-script

echo "Installing Grunt and Grunt packages..."
  npm install -g grunt

echo "Installing Wintersmith for creating static websites..."
  npm install -g wintersmith
 
echo "Installing JSHint to validate Javascript code..."
  npm install -g jshint

echo "Installing Uglify for minifying Javascript code..."
  npm install -g uglify-js

echo "Installing Handlebars templating engine..."
  npm install -g handlebars

echo "Installing Jade templating engine..."
  npm install -g jade

echo "Installing JS2Coffee for converting projects to Coffeescript..."
  npm install -g js2coffee

